INSERT INTO
games(name, picture_url)
VALUES
    ('Among Us', 'https://steamcdn-a.akamaihd.net/steam/apps/945360/capsule_184x69.jpg'),
    ('Counter Strike: GO', 'https://steamcdn-a.akamaihd.net/steam/apps/730/capsule_184x69.jpg'),
    ('DOTA 2', 'https://steamcdn-a.akamaihd.net/steam/apps/570/capsule_184x69.jpg'),
    ('Destiny 2', 'https://steamcdn-a.akamaihd.net/steam/apps/1085660/capsule_184x69.jpg'),
    ('Player Unknown''s Battegrounds', 'https://steamcdn-a.akamaihd.net/steam/apps/578080/capsule_184x69.jpg'),
    ('GTAV', 'https://steamcdn-a.akamaihd.net/steam/apps/271590/capsule_184x69.jpg'),
    ('Apex Legends', 'https://steamcdn-a.akamaihd.net/steam/apps/1172470/capsule_184x69.jpg'),
    ('TF2', 'https://steamcdn-a.akamaihd.net/steam/apps/440/capsule_184x69.jpg'),
    ('Rust', 'https://steamcdn-a.akamaihd.net/steam/apps/252490/capsule_184x69.jpg'),
    ('Rainbow Six Siege', 'https://steamcdn-a.akamaihd.net/steam/apps/359550/capsule_184x69.jpg'),
    ('ARK: Survival Evolved', 'https://steamcdn-a.akamaihd.net/steam/apps/346110/capsule_184x69.jpg'),
    ('Warframe', 'https://steamcdn-a.akamaihd.net/steam/apps/230410/capsule_184x69.jpg'),
    ('War Thunder', 'https://steamcdn-a.akamaihd.net/steam/apps/236390/capsule_184x69.jpg'),
    ('Dead By Daylight', 'https://steamcdn-a.akamaihd.net/steam/apps/381210/capsule_184x69.jpg'),
    ('Civilization VI', 'https://steamcdn-a.akamaihd.net/steam/apps/289070/capsule_184x69.jpg'),
    ('Hearts of Iron IV', 'https://steamcdn-a.akamaihd.net/steam/apps/394360/capsule_184x69.jpg'),
    ('Terraria', 'https://steamcdn-a.akamaihd.net/steam/apps/105600/capsule_184x69.jpg'),
    ('Phasmophobia', 'https://steamcdn-a.akamaihd.net/steam/apps/739630/capsule_184x69.jpg');
    -- ('Garry''s Mod', ''),
    -- ('World of Tanks Blitz', ''),
    -- ('DayZ', ''),
    -- ('Spacewar', ''),
    -- ('Brawlhalla', ''),
    -- ('PAYDAY 2', ''),
    -- ('Civilization V', ''),
    -- ('7 Days to Die', ''),
    -- ('Unturned', ''),
    -- ('The Elder Scrolls Online', ''),
    -- ('Crusader Kings III', ''),
    -- ('Fall Guys', ''),
    -- ('Final Fantasy XIV Online', ''),
    -- ('Left 4 Dead 2', ''),
    -- ('Rocket League', ''),
    -- ('Monster Hunter: World', '');